# Generated by Django 4.1.1 on 2022-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dateofbirth",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
