# Generated by Django 4.1.1 on 2022-11-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_patient_dateofbirth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="dateofbirth",
            new_name="dob",
        ),
    ]
