# Generated by Django 4.1.3 on 2022-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_dateofbirth_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CMS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
