# Generated by Django 4.1.3 on 2022-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_patient_cms_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Rejectiondis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='refferinghospital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CMS',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
