# Generated by Django 4.1.3 on 2022-11-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_patient_rejectiondis_patient_refferinghospital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='refferinghospital',
            new_name='ReferringHospital',
        ),
    ]
