# Generated by Django 4.1.3 on 2022-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_refferinghospital_patient_referringhospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CMS',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
