# Generated by Django 4.1.3 on 2022-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_patient_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CMS',
            field=models.CharField(max_length=3),
        ),
    ]
