# Generated by Django 4.1.3 on 2022-12-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_patient_adls_patient_assessmentandrationale_and_more'),
        ('base', '0010_alter_patient_cms'),
    ]

    operations = [
    ]
