# Generated by Django 4.1.3 on 2022-12-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_patient_historyofpresentillness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Concentration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Langauge',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Memory',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Orientation',
        ),
    ]
