# Generated by Django 4.1.3 on 2022-12-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_patient_concentration_remove_patient_langauge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Concentration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Langauge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Memory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Orientation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
