from django.db import connections
from django.db import models

# Create your models here.
class Patient(models.Model):
    patientname = models.CharField(max_length=100)
    age = models.CharField(max_length=100, blank=True)
    dob = models.CharField(max_length=100, blank=True)
    sex = models.CharField(max_length=100, blank=True)
    adress1 = models.CharField(max_length=100, blank=True)
    adress2 = models.CharField(max_length=100, blank=True)
    workphone = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    st = models.CharField(max_length=100, blank=True)
    zip = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    county = models.CharField(max_length=100, blank=True)
    homephone = models.CharField(max_length=100, blank=True)
    primaryinsurance = models.CharField(max_length=100, blank=True)
    insurancename1 = models.CharField(max_length=100, blank=True)
    ID1 = models.CharField(max_length=100, blank=True)
    GP1 = models.CharField(max_length=100, blank=True)
    EFF1 = models.CharField(max_length=100, blank=True)
    EXP1 = models.CharField(max_length=100, blank=True)
    secondaryinsurance = models.CharField(max_length=100, blank=True)
    insurancename2 = models.CharField(max_length=100, blank=True)
    ID2 = models.CharField(max_length=100, blank=True)
    GP2 = models.CharField(max_length=100, blank=True)
    EFF2 = models.CharField(max_length=100, blank=True)
    EXP2 = models.CharField(max_length=100, blank=True)
    tertiaryinsurance = models.CharField(max_length=100, blank=True)
    insurancename3 = models.CharField(max_length=100, blank=True)
    ID3 = models.CharField(max_length=100, blank=True)
    GP3 = models.CharField(max_length=100, blank=True)
    EFF3 = models.CharField(max_length=100, blank=True)
    EXP3 = models.CharField(max_length=100, blank=True)
    referringmd = models.CharField(max_length=100, blank=True)
    ReferringHospital = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    fax = models.CharField(max_length=100, blank=True)
    NearestRelativeName = models.CharField(max_length=100, blank=True)
    NearestRelativeRelation = models.CharField(max_length=100, blank=True)
    NearestRelativeAddress = models.CharField(max_length=100, blank=True)
    NearestRelativeHomePhone = models.CharField(max_length=100, blank=True)
    NearestRelativeCity = models.CharField(max_length=100, blank=True)
    NearestRelativeST = models.CharField(max_length=100, blank=True)
    NearestRelativeZip = models.CharField(max_length=100, blank=True)
    NearestRelativeWorkPhone = models.CharField(max_length=100, blank=True)
    NearestRelativeWorkPhoneExt = models.CharField(max_length=100, blank=True)
    Status = models.CharField(max_length=100,blank=True, null=True)
    Diagnosis = models.CharField(max_length=100,blank=True, null=True)
    CMS = models.CharField(max_length=3,blank=True)
    Rejectiondis = models.CharField(max_length=100,blank=True, null=True)
    ReferralDate = models.CharField(max_length=100,blank=True, null=True)
    Assignee = models.CharField(max_length=100,blank=True, null=True)
    PresentHistory = models.CharField(max_length=300,blank=True, null=True)
    PastHistory = models.CharField(max_length=300,blank=True, null=True)
    Orientation = models.CharField(max_length=100,blank=True, null=True)
    Concentration = models.CharField(max_length=100,blank=True, null=True) 
    Memory = models.CharField(max_length=100,blank=True, null=True)
    Langauge = models.CharField(max_length=100,blank=True, null=True)
    muskuloskeletal = models.CharField(max_length=100, blank=True)
    ImpressionAndPlan = models.CharField(max_length=100, blank=True)
    impairments = models.CharField(max_length=100, blank=True)
    TreatingDiagnosis = models.CharField(max_length=100, blank=True)
    RehabPotential = models.CharField(max_length=100, blank=True)
    AssessmentAndRationale = models.CharField(max_length=100, blank=True)
    DispositionRecommendations = models.CharField(max_length=100, blank=True)
    frequency = models.CharField(max_length=100, blank=True)
    duration = models.CharField(max_length=100, blank=True)
    DurationUnit = models.CharField(max_length=100, blank=True)
    TPIPlanned = models.CharField(max_length=100, blank=True)
    caregiver = models.CharField(max_length=100, blank=True)
    MedicalDiagnosis = models.CharField(max_length=100, blank=True)
    OnsetDate = models.CharField(max_length=100, blank=True)
    PatientPrecautions = models.CharField(max_length=100, blank=True)
    LeftUE = models.CharField(max_length=100, blank=True)
    RightUE = models.CharField(max_length=100, blank=True)
    LeftLE = models.CharField(max_length=100, blank=True)
    RightLE = models.CharField(max_length=100, blank=True)
    transfers = models.CharField(max_length=100, blank=True)
    BedMobility = models.CharField(max_length=100, blank=True)
    ADLs = models.CharField(max_length=100, blank=True)
    ambulation = models.CharField(max_length=100, blank=True)
    auditory = models.CharField(max_length=100, blank=True)
    vision = models.CharField(max_length=100, blank=True)
    SubjectiveInformation = models.CharField(max_length=100, blank=True)
    LivingSituation = models.CharField(max_length=100, blank=True)
    CognitionLOC = models.CharField(max_length=100, blank=True)
    CognitionOrientation = models.CharField(max_length=100, blank=True)
    SupineToSit = models.CharField(max_length=100, blank=True)
    SitToStand = models.CharField(max_length=100, blank=True)
    StandToSit = models.CharField(max_length=100, blank=True)
    BedToChair = models.CharField(max_length=100, blank=True)
    gait = models.CharField(max_length=100, blank=True)

    
    def __str__(self):
        return self.patientname 

    def clean(self):
        if self.CMS:
            self.CMS = self.CMS.strip()

    

